# Generated by Django 2.1.7 on 2019-03-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.URLField(unique=True, verbose_name='封面')),
                ('url', models.URLField(unique=True, verbose_name='链接')),
                ('title', models.CharField(max_length=200, verbose_name='电影标题')),
                ('info', models.CharField(max_length=300, verbose_name='上演信息')),
                ('rate', models.FloatField(default=0, verbose_name='评分')),
                ('commit', models.CharField(max_length=200, verbose_name='短评')),
            ],
        ),
    ]
